use zinc_internal::{__ZincBuiltinMeta, __ZincChannel, __ZincConstMeta, __ZincEnumMeta, __ZincFieldMeta, __ZincFunctionMeta, __ZincFunctionParameterMeta, __ZincMethodMeta, __ZincMethodParameterMeta, __ZincStructMeta, __ZincTypeMeta, __ZincVariableMeta, __ZincVariantMeta};

static METADATA_01_SYMBOL_META__APP_NAME: std::sync::LazyLock<String> = std::sync::LazyLock::new(|| String::from("zinc"));

#[derive(Clone)]
enum metadata_01_symbol_meta__Status {
    Ready,
    Busy,
}

impl metadata_01_symbol_meta__Status {
    fn banner(prefix: String) -> String {
        return format!("{}:status", prefix);
    }
}

struct metadata_01_symbol_meta__Profile {
    pub version: i64,
    pub name: String,
}

impl Default for metadata_01_symbol_meta__Profile {
    fn default() -> Self {
        Self { version: 1, name: String::new() }
    }
}

impl metadata_01_symbol_meta__Profile {
    fn label(&self, prefix: String) -> String {
        return format!("{}:{}:{}", prefix, self.name, (*METADATA_01_SYMBOL_META__APP_NAME).clone());
    }
    fn build_tag(suffix: String) -> String {
        return format!("{}:build", suffix);
    }
}

fn metadata_01_symbol_meta__inspect_i64(count: i64) -> i64 {
    let local = count;
    let typed: String = (*METADATA_01_SYMBOL_META__APP_NAME).clone();
    println!("{}", 32);
    println!("{:?}", __ZincFunctionParameterMeta { kind: String::from("parameter"), name: String::from("count"), fqn: String::from("metadata/01_symbol_meta/inspect/count"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 29, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false });
    println!("{}", String::from("inspect"));
    println!("{}", String::from("i64"));
    println!("{:?}", __ZincVariableMeta { kind: String::from("variable"), name: String::from("local"), fqn: String::from("metadata/01_symbol_meta/inspect/local"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 30, is_public: false, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: false, is_mutated: false, is_shadow: false });
    println!("{}", String::from("inspect"));
    println!("{}", String::from("i64"));
    println!("{}", true);
    println!("{:?}", __ZincConstMeta { kind: String::from("const"), name: String::from("APP_NAME"), fqn: String::from("metadata/01_symbol_meta/APP_NAME"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 1, is_public: true, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, value_text: String::from("\"zinc\"") });
    println!("{:?}", __ZincFunctionMeta { kind: String::from("function"), name: String::from("inspect"), fqn: String::from("metadata/01_symbol_meta/inspect"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 29, is_public: true, params: vec![__ZincFunctionParameterMeta { kind: String::from("parameter"), name: String::from("count"), fqn: String::from("metadata/01_symbol_meta/inspect/count"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 29, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false }], return_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, is_async: false });
    println!("{:?}", __ZincFunctionParameterMeta { kind: String::from("parameter"), name: String::from("count"), fqn: String::from("metadata/01_symbol_meta/inspect/count"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 29, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false });
    println!("{}", String::from("inspect"));
    println!("{:?}", __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() });
    println!("{:?}", __ZincFunctionMeta { kind: String::from("function"), name: String::from("ping"), fqn: String::from("metadata/01_symbol_meta/ping"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 25, is_public: true, params: Vec::<__ZincFunctionParameterMeta>::new(), return_type: __ZincTypeMeta { kind: String::from("unknown"), name: String::from("unknown"), fqn: String::from("unknown"), family_name: String::from("unknown"), family_fqn: String::from("unknown"), args: Vec::<__ZincTypeMeta>::new(), is_named: false, is_bounded: false, infer_slots: Vec::<String>::new() }, is_async: true });
    println!("{:?}", __ZincBuiltinMeta { kind: String::from("builtin"), name: String::from("print"), fqn: String::from("builtin/print"), module_fqn: String::from("builtin"), file: String::from(""), line_num: 0, is_public: true, params: Vec::<__ZincFunctionParameterMeta>::new(), return_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("()"), fqn: String::from("()"), family_name: String::from("()"), family_fqn: String::from("()"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, is_async: false });
    return count;
}

#[tokio::main]
async fn main() {
    let profile = metadata_01_symbol_meta__Profile { version: 1, name: String::from("Ada") };
    let queue = __ZincChannel::<i64>::bounded(1);
    queue.send(11).await;
    println!("{:?}", __ZincStructMeta { kind: String::from("struct"), name: String::from("Profile"), fqn: String::from("metadata/01_symbol_meta/Profile"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 12, is_public: true, type_info: __ZincTypeMeta { kind: String::from("struct"), name: String::from("Profile"), fqn: String::from("metadata/01_symbol_meta/Profile"), family_name: String::from("Profile"), family_fqn: String::from("metadata/01_symbol_meta/Profile"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() } });
    println!("{:?}", __ZincTypeMeta { kind: String::from("struct"), name: String::from("Profile"), fqn: String::from("metadata/01_symbol_meta/Profile"), family_name: String::from("Profile"), family_fqn: String::from("metadata/01_symbol_meta/Profile"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() });
    println!("{:?}", vec![__ZincFieldMeta { kind: String::from("field"), name: String::from("version"), fqn: String::from("metadata/01_symbol_meta/Profile/version"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 13, is_public: true, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, index: 0, is_const: true, has_default: true, is_declared: true, source_component_fqn: String::from("") }, __ZincFieldMeta { kind: String::from("field"), name: String::from("name"), fqn: String::from("metadata/01_symbol_meta/Profile/name"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 14, is_public: true, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, index: 1, is_const: false, has_default: false, is_declared: true, source_component_fqn: String::from("") }]);
    println!("{:?}", __ZincEnumMeta { kind: String::from("enum"), name: String::from("Status"), fqn: String::from("metadata/01_symbol_meta/Status"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 3, is_public: true, type_info: __ZincTypeMeta { kind: String::from("enum"), name: String::from("Status"), fqn: String::from("metadata/01_symbol_meta/Status"), family_name: String::from("Status"), family_fqn: String::from("metadata/01_symbol_meta/Status"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() } });
    println!("{:?}", __ZincTypeMeta { kind: String::from("enum"), name: String::from("Status"), fqn: String::from("metadata/01_symbol_meta/Status"), family_name: String::from("Status"), family_fqn: String::from("metadata/01_symbol_meta/Status"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() });
    println!("{:?}", vec![__ZincVariantMeta { kind: String::from("variant"), name: String::from("Ready"), fqn: String::from("metadata/01_symbol_meta/Status/Ready"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 4, is_public: true, index: 0 }, __ZincVariantMeta { kind: String::from("variant"), name: String::from("Busy"), fqn: String::from("metadata/01_symbol_meta/Status/Busy"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 5, is_public: true, index: 1 }]);
    println!("{:?}", __ZincVariantMeta { kind: String::from("variant"), name: String::from("Ready"), fqn: String::from("metadata/01_symbol_meta/Status/Ready"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 4, is_public: true, index: 0 });
    println!("{}", String::from("Status"));
    println!("{:?}", __ZincMethodMeta { kind: String::from("method"), name: String::from("build_tag"), fqn: String::from("metadata/01_symbol_meta/Profile/build_tag"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 20, is_public: true, params: vec![__ZincMethodParameterMeta { kind: String::from("parameter"), name: String::from("suffix"), fqn: String::from("metadata/01_symbol_meta/Profile/build_tag/suffix"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 20, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false }], return_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, is_async: false, is_static: true, is_declared: true });
    println!("{:?}", __ZincMethodParameterMeta { kind: String::from("parameter"), name: String::from("suffix"), fqn: String::from("metadata/01_symbol_meta/Profile/build_tag/suffix"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 20, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false });
    println!("{:?}", __ZincFieldMeta { kind: String::from("field"), name: String::from("name"), fqn: String::from("metadata/01_symbol_meta/Profile/name"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 14, is_public: true, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, index: 1, is_const: false, has_default: false, is_declared: true, source_component_fqn: String::from("") });
    println!("{}", String::from("Profile"));
    println!("{:?}", __ZincMethodMeta { kind: String::from("method"), name: String::from("label"), fqn: String::from("metadata/01_symbol_meta/Profile/label"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 16, is_public: true, params: vec![__ZincMethodParameterMeta { kind: String::from("parameter"), name: String::from("prefix"), fqn: String::from("metadata/01_symbol_meta/Profile/label/prefix"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 16, is_public: false, index: 0, value_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, declared_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, has_declared_type: true, has_default: false }], return_type: __ZincTypeMeta { kind: String::from("primitive"), name: String::from("String"), fqn: String::from("String"), family_name: String::from("String"), family_fqn: String::from("String"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }, is_async: false, is_static: false, is_declared: true });
    println!("{}", String::from("Profile"));
    println!("{:?}", __ZincVariableMeta { kind: String::from("variable"), name: String::from("queue"), fqn: String::from("metadata/01_symbol_meta/main/queue"), module_fqn: String::from("metadata/01_symbol_meta"), file: String::from("/Users/eric/code/zinc/test/zinc_source/metadata/01_symbol_meta.zn"), line_num: 52, is_public: false, value_type: __ZincTypeMeta { kind: String::from("channel"), name: String::from("channel<i64>"), fqn: String::from("channel<i64>"), family_name: String::from("channel"), family_fqn: String::from("channel"), args: vec![__ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }], is_named: false, is_bounded: true, infer_slots: Vec::<String>::new() }, has_declared_type: false, is_mutated: false, is_shadow: false });
    println!("{:?}", __ZincTypeMeta { kind: String::from("channel"), name: String::from("channel<i64>"), fqn: String::from("channel<i64>"), family_name: String::from("channel"), family_fqn: String::from("channel"), args: vec![__ZincTypeMeta { kind: String::from("primitive"), name: String::from("i64"), fqn: String::from("i64"), family_name: String::from("i64"), family_fqn: String::from("i64"), args: Vec::<__ZincTypeMeta>::new(), is_named: true, is_bounded: false, infer_slots: Vec::<String>::new() }], is_named: false, is_bounded: true, infer_slots: Vec::<String>::new() });
    println!("{}", String::from("i64"));
    println!("{}", true);
    println!("{}", String::from("builtin/type"));
    println!("{}", metadata_01_symbol_meta__inspect_i64(5));
    println!("{}", profile.label(String::from("hi")));
    println!("{}", metadata_01_symbol_meta__Profile::build_tag(String::from("prod")));
    println!("{}", metadata_01_symbol_meta__Status::banner((*METADATA_01_SYMBOL_META__APP_NAME).clone()));
}