# Install antigen if not found. 
# https://github.com/zsh-users/antigen
# You can uninstall antigen with
#   rm -rf $HOME/.antigen*
ANTIGEN_FILE="$HOME/.antigen.zsh"
if [ ! -f "$ANTIGEN_FILE" ]; then
    echo "Installing antigen!..."
    curl -sL git.io/antigen > "$ANTIGEN_FILE"
fi

# Load antigen
source "$ANTIGEN_FILE"
antigen use oh-my-zsh

# Git status arrows in the shell prompt
antigen bundle git

# Auto-suggest lookup https://github.com/zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-autosuggestions

# Use pure theme https://github.com/sindresorhus/pure
antigen bundle mafredri/zsh-async@main
antigen bundle sindresorhus/pure@main

# Syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting

# Apply antigen settings
antigen apply

alias ".."="cd .."
alias gs="git status"
